Makefile_TARGETS = \
	Makefile.dep \
	src/Makefile \
	build/Makefile

Makefile_DEPS = \
	"M:/SYSC 4805/ElevatorProject/Elevator_Control_System/Small_Elevator_System/Small_Elevator_System.rtmdl" \
	"C:/Program Files/Rational/Rose RealTime/C++/RTComponents.rtcmppkg" \
	"C:/Program Files/Rational/Rose RealTime/C++/RTClasses.rtlogpkg"

